collections_config:
  landing-pages:
    schemas:
      page:
        path: .cloudcannon/schemas/page.html
    _enabled_editors:
      - visual
  site-pages:
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    description: Core pages of the site
    icon: hub

_inputs:
  layout:
    hidden: true