source: src
collections_config_override: true
collections_config:
  authors:
    description: The authors of blog posts
    output: false
    path: 'collections/authors'
    schemas:
      default:
        path: .cloudcannon/schemas/author.md
    _enabled_editors:
      - content
    icon: face
    filter:
      exclude:
        - authors.11tydata.js
  cheat-sheets:
    description: Reference guides for SSGs
    output: true
    path: 'collections/cheat-sheets'
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    _enabled_editors:
      - content
    icon: history_edu
    filter:
      exclude:
        - cheat-sheets.json
  jekyll-cheat-sheets:
    description: Data for the Jekyll cheat sheet
    output: false
    path: 'collections/jekyll-cheat-sheet'
    schemas:
      default:
        path: .cloudcannon/schemas/cheat.md
    _enabled_editors:
      - content
    icon: science
    filter:
      exclude:
        - jekyll-cheat-sheet.json
  landing-pages:
    description: Landing pages built entirely with the page builder
    output: true
    path: 'collections/landing-pages'
    schemas:
      default:
        path: .cloudcannon/schemas/page.html
    _enabled_editors:
      - visual
    icon: flight_land
  site-pages:
    path: 'collections/site-pages'
    output: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    description: Core pages of the site
    icon: hub
    filter:
      exclude:
        - tags.html
    _inputs:
      permalink:
        hidden: true
      pagination:
        hidden: true
  ssg-pages:
    description: SSG Landing Pages
    output: true
    path: 'collections/ssg-pages'
    schemas:
      default:
        path: .cloudcannon/schemas/page.html
    _enabled_editors:
      - visual
    icon: nest_eco_leaf
  case-studies:
    path: 'collections/case-studies'
    output: true
    description: Customers who say great things about CC
    icon: account_circle
    schemas:
      default:
        path: .cloudcannon/schemas/case-study.md
    filter:
      exclude:
        - case-studies.json
    _inputs:
      heading:
        comment: Is used on the case study card
      categories:
        type: multiselect
        options:
          values:
            - Agency
            - Documentation
            - "Company sites"
            - Business
            - Microsites
      weight:
        type: number
        comment: The order the case study shows on the customers page
      path:
        type: image
      logo:
        type: image
        comment: Ideally an SVG, displayed in on the case study card and page.
      description:
        type: textarea
        comment: Shows under the title on the case study page

_inputs:
  layout:
    hidden: true
  uuid:
    instance_value: UUID
    hidden: true