source: src
collections_config_override: true
collections_config:
  landing-pages:
    description: Landing pages built entirely with the page builder
    output: true
    path: 'collections/landing-pages'
    schemas:
      default:
        path: .cloudcannon/schemas/page.html
    _enabled_editors:
      - visual
    icon: flight_land
  site-pages:
    path: 'collections/site-pages'
    output: true
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
    description: Core pages of the site
    icon: hub
  case-studies:
    path: 'collections/case-studies'
    output: true
    description: Customers who say great things about CC
    icon: account_circle
    schemas:
      default:
        path: .cloudcannon/schemas/case-study.md
    _inputs:
      categories:
        type: multiselect
        options:
          values:
            - Agency
            - Documentation
            - "Company sites"
            - Business
            - Microsites

_inputs:
  layout:
    hidden: true
  uuid:
    instance_value: UUID
    hidden: true