# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Quote"
  description: "Displays a quote from a customer"
  icon: person_pin
  tags: ['content']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    case_study_quote:
  styles:
    background: 
    border: false
    desktop:
      margin:
        top: 0
        bottom: 0
      block_alignment:
        align_block: center
      transform:
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
    tablet:
      margin:
        active: false
        top: 0
        bottom: 0
      block_alignment:
        active: false
        align_block: center
      transform:
        active: false
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0
    mobile:
      margin:
        active: false
        top: 0
        bottom: 0
      block_alignment:
        active: false
        align_block: center
      transform:
        active: false
        scale: 1
        translate_x: 0
        translate_y: 0
        rotate: 0
        skew: 0

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  case_study_quote:
    type: select
    options:
      values: collections.case-study-quote
  active:
    comment: These values won't be used unless active is enabled.
    type: switch
  desktop:
    comments: Styles for Desktop, unless overridden will also be used for tablet and mobile.
  tablet:
    comments: Styles for Tablet, unless overridden will also be used for mobile.
  mobile:
    comments: Styles for mobile.
  logo_blocks:
    comment: The list of logos
  margin:
    comment: Adjust the spacing between this component and others. Can be negative for overlapping.
  align_block:
    comment: Aligns the entire block
    options:
      values:
        - left
        - center
  top:
    type: number
  right:
    type: number
  bottom:
    type: number
  left:
    type: number
  background:
    type: select
    comment: The background color for the entire quote
    options:
      values:
        - white
        - caramel
        - sky
        - sea
        - cc-blue
        - ash
        - night