# Metadata about this component, to be used in the CMS
spec:
  structures:
    - blocks
  label: "Button Holder"
  description: "A container for buttons"
  icon: open_in_browser
  tags: ['content']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    button_blocks:
  styles:
    margin:
      top: 0
      bottom: 0
    align: center
# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  margin:
    comment: Adjust the spacing between the button holder and other components. Can be negative for overlapping.
  top:
    type: number
  right:
    type: number
  bottom:
    type: number
  left:
    type: number
  align:
    comment: How the buttons are aligned
    type: select
    options:
      values:
        - left
        - center
