# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - blocks
  label: "Container"
  description: The main building block for pages. Will contain many smaller components.
  icon: web_asset
  tags: ['containers']

# Defines the structure of this component, as well as the default values
blueprint:
  label:
  background: 
  rounded: none
  margin:
    top: 0
    right: 0
    bottom: 0
    left: 0
  size: normal
  align: none
  blocks:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  label:
    comment: This is used to help identify the section in CloudCannon. It's not output anywhere on the page.
  blocks:
    comments: Add components inside this section.
  background:
    type: select
    comment: The background color for the entire section
    options:
      values:
        - caramel
        - sky
        - cc-blue
        - ash
        - night
        - sun-spot
  rounded:
    type: select
    comment: Sets the style of rounded corners on the section.
    options:
      values:
        - none
        - top
        - full
  margin:
    comment: Adjust the spacing between this section and others. Can be negative for overlapping.
  top:
    type: number
  right:
    type: number
  bottom:
    type: number
  left:
    type: number
  size:
    type: select
    comment: Adjust the width of the section
    options:
      values:
        - normal
        - small
  align:
    comment: Customize how the section is aligned on the page
    type: select
    options:
      values:
        - none
        - center
