# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - blocks
  label: "Emoji heading"
  description: A special type of heading with a emoji, sub heading, and main heading
  icon: waving_hand
  tags: ['content']

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    title:
    emoji:
    sub_title: 
  styles:
    width:
    text_alignment:
    margin:
      top: 0
      bottom: 0


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  title:
    comment: The main heading
  sub_title:
    comment: The sub heading
  emoji:
    comment: An optional emoji to display above the headings
  width:
    comment: The width of the text block
    type: select 
    options:
      values:
        - tight
        - full
  margin:
    comment: Adjust the spacing between the component and other components. Can be negative for overlapping.
  top:
    type: number
  bottom:
    type: number
