# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Simple Emoji-heading"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    title:
  styles:
    width:
    center_text:
    margin:
      top: 0
      bottom: 0


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
