site_url: https://cloudcannon.com
site_name: CloudCannon
site_title: CloudCannon
favicon: "/images/favicon.svg"
description: The Jamstack CMS marketers and developers love to use
twitter_site: "@CloudCannon"
image: "https://cc-dam.imgix.net/marketing/uploads/homepage-meta.jpg"
image_alt: "Showcasing editor options"
