# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
    - blocks
  label: "Case studies"
  description:
  icon:
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    case_studies: []
  styles:
    margin:
      top: 0
      right: 0
      bottom: 0
      left: 0
    padding:
      top: 0
      right: 0
      bottom: 0
      left: 0


# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  case_studies:
    type: array
  case_studies[*]:
    type: select
    options:
      values: collections.case-studies
      value_key: uuid
      preview:
        text:
          - key: title