# Metadata about this component, to be used in the CMS
spec:
  structures:
    - button_blocks
  label: "Button"
  description: A button you click on and it does something
  icon: smart_button
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  content:
    text: "I'm a button"
    link: "/"
  styles:
    style: "normal"
    size: "normal"

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  style:
    type: select
    options:
      values:
        - normal
        - outline
        - outline-white
        - white
  size:
    type: select
    options:
      values:
        - normal
        - big
